### ISSUE TITLE
Story 4 - As a conference owner, I want to create an event so that I can manage it on the app.

### ISSUE THREAD

**Issue by joanaferreira0011** [FEUP-ESOF-2020-21/open-cx-t7g1-last4#3]
As a conference owner, I want to create an event so that I can manage it on the app.

**Comment by zemacedo99** [comment]
Em falta: 
Corrigir a questão da data, não permite colocar datas futuras,
Adicionar data de inicio e data de fim

**Comment by zemacedo99** [comment]
E colocar esse evento na db
